package lect0531;

import java.util.Scanner;

public class exceptionHander {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner s = new Scanner(System.in);
		System.out.println("숫자를 입력하세요.");
		int num1 = s.nextInt();

		// try 블록
		try {
			int num2 = 10 / num1;
			System.out.println(num2);
		} // catch 블록
		catch (Exception e) {
			System.out.println("올바른 숫자를 입력하세요.");
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
		System.out.println("try~catch 블록의 외부 문장입니다.");
	}

}
